export const DEFAULT_PRODUCTS = [
  { name: 'Acetolim SR', category: 'Tablets', composition: 'Acetazolamide 250mg (SR)', description: 'Sustained-release carbonic anhydrase inhibitor for glaucoma', catalogSlide: 2, isSeeded: true },
  { name: 'Beporiz', category: 'Eye Drops', composition: 'Bepotastine Besilate 1.5%', description: 'Antihistamine for allergic conjunctivitis & itching', catalogSlide: 3, isSeeded: true },
  { name: 'Brohit', category: 'Eye Drops', composition: 'Bromfenac Sodium 0.09%', description: 'NSAID for post-cataract surgery inflammation & pain', catalogSlide: 4, isSeeded: true },
  { name: 'Brohit-M', category: 'Eye Drops', composition: 'Bromfenac 0.09% + Moxifloxacin 0.5%', description: 'Anti-inflammatory + antibiotic combo for post-surgical care', catalogSlide: 5, isSeeded: true },
  { name: 'Catahit', category: 'Eye Drops', composition: 'Sodium Carboxymethylcellulose 1% + Glycerin 0.9% + N-Acetyl Carnosine 1%', description: 'Anti-cataract eye drops for lens clarity', catalogSlide: 6, isSeeded: true },
  { name: 'Cycloact', category: 'Eye Drops', composition: 'Cyclopentolate HCl 1%', description: 'Mydriatic & cycloplegic for diagnostic procedures', catalogSlide: 7, isSeeded: true },
  { name: 'Difunice', category: 'Eye Drops', composition: 'Difluprednate 0.05%', description: 'Potent corticosteroid for post-operative ocular inflammation & pain', catalogSlide: 8, isSeeded: true },
  { name: 'Difunice-MF', category: 'Eye Drops', composition: 'Difluprednate 0.05% + Moxifloxacin 0.5%', description: 'Steroid-antibiotic combination for post-surgical inflammation', catalogSlide: 9, isSeeded: true },
  { name: 'Fluroriz', category: 'Eye Drops', composition: 'Fluorometholone 0.1%', description: 'Mild steroid for steroid-responsive inflammatory conditions', catalogSlide: 10, isSeeded: true },
  { name: 'Glulare', category: 'Eye Drops', composition: 'Latanoprost 0.005%', description: 'Prostaglandin analogue for open-angle glaucoma & ocular hypertension', catalogSlide: 11, isSeeded: true },
  { name: 'Hayuvet', category: 'Eye Drops', composition: 'Sodium Hyaluronate 0.1%', description: 'Lubricant for dry eye syndrome', catalogSlide: 12, isSeeded: true },
  { name: 'Hayuvet-5', category: 'Eye Drops', composition: 'Sodium Hyaluronate 0.5%', description: 'Higher concentration lubricant for moderate-severe dry eyes', catalogSlide: 13, isSeeded: true },
  { name: 'Hayuvet-D', category: 'Eye Drops', composition: 'Sodium Hyaluronate 0.1% + Dexpanthenol 2%', description: 'Lubricant with healing agent for dry & damaged cornea', catalogSlide: 14, isSeeded: true },
  { name: 'Hayuvet Ultra', category: 'Eye Drops', composition: 'Sodium Hyaluronate 0.18%', description: 'Ultra lubricant for dry eye relief', catalogSlide: 15, isSeeded: true },
  { name: 'Hayuvet-Max', category: 'Eye Drops', composition: 'Sodium Hyaluronate 0.3%', description: 'Maximum strength lubricant for severe dry eyes', catalogSlide: 16, isSeeded: true },
  { name: 'Heltroz', category: 'Eye Drops', composition: 'Loteprednol Etabonate 0.5%', description: 'Soft steroid for post-operative inflammation & allergic conjunctivitis', catalogSlide: 17, isSeeded: true },
  { name: 'Homamic', category: 'Eye Drops', composition: 'Homatropine Hydrobromide 2%', description: 'Cycloplegic & mydriatic for refraction & uveitis', catalogSlide: 18, isSeeded: true },
  { name: 'Hycotic', category: 'Eye Drops', composition: 'Hydroxypropyl Methylcellulose 2% (HPMC)', description: 'Viscous lubricant for dry eye comfort', catalogSlide: 19, isSeeded: true },
  { name: 'LocFresh Eye Drops', category: 'Eye Drops', composition: 'CMC 0.5% + Glycerin 0.9%', description: 'Lubricant for everyday dry eye relief', catalogSlide: 20, isSeeded: true },
  { name: 'LocFresh Gel', category: 'Eye Gel', composition: 'CMC 1% + Glycerin 0.9%', description: 'Long-lasting gel lubricant for dry eyes', catalogSlide: 21, isSeeded: true },
  { name: 'LocFresh Plus', category: 'Eye Drops', composition: 'CMC 0.5% + Glycerin 0.9% + Stabilized Oxychloro Complex', description: 'Enhanced lubricant with antimicrobial protection', catalogSlide: 22, isSeeded: true },
  { name: 'LocFresh Soft', category: 'Eye Drops', composition: 'CMC 0.25% + Glycerin 0.9%', description: 'Gentle lubricant for mild dry eyes', catalogSlide: 23, isSeeded: true },
  { name: 'LocFresh Ultra', category: 'Eye Drops', composition: 'CMC 0.5% + Sodium Hyaluronate 0.1%', description: 'Dual-action ultra lubricant', catalogSlide: 24, isSeeded: true },
  { name: 'LocFresh Xtra', category: 'Eye Drops', composition: 'CMC 1% + Glycerin 0.9%', description: 'Extra strength lubricant for severe dryness', catalogSlide: 25, isSeeded: true },
  { name: 'LocFresh Ointment', category: 'Eye Ointment', composition: 'White Petrolatum + Mineral Oil + Lanolin', description: 'Nighttime ointment for severe dry eyes', catalogSlide: 26, isSeeded: true },
  { name: 'Lytonol Eye Drops', category: 'Eye Drops', composition: 'Phenylephrine 5% + Tropicamide 0.8%', description: 'Mydriatic combination for pupil dilation', catalogSlide: 27, isSeeded: true },
  { name: 'Lytonol Ointment', category: 'Eye Ointment', composition: 'Phenylephrine 5% + Tropicamide 0.8%', description: 'Ointment form mydriatic', catalogSlide: 28, isSeeded: true },
  { name: 'Lytonol LS', category: 'Eye Drops', composition: 'Phenylephrine 2.5% + Tropicamide 0.5%', description: 'Low-strength mydriatic for pediatric use', catalogSlide: 29, isSeeded: true },
  { name: 'Myloact', category: 'Eye Drops', composition: 'Cyclosporine 0.05%', description: 'Immunomodulator for chronic dry eye disease', catalogSlide: 30, isSeeded: true },
  { name: 'Myloact Gold', category: 'Eye Drops', composition: 'Cyclosporine 0.09%', description: 'Higher-strength immunomodulator for severe dry eye', catalogSlide: 31, isSeeded: true },
  { name: 'Myloact Max', category: 'Capsules', composition: 'Cyclosporine 0.1%', description: 'Maximum strength immunomodulator for dry eye', catalogSlide: 32, isSeeded: true },
  { name: 'Myloact-M', category: 'Eye Drops', composition: 'Cyclosporine 0.05% + HPMC', description: 'Immunomodulator with enhanced lubrication', catalogSlide: 33, isSeeded: true },
  { name: 'Mynapro-D 500', category: 'Capsules', composition: 'Methylcobalamin 1500mcg + Vitamin D3 1000IU + Folic Acid + ALA', description: 'Neuro-ophthalmic nutritional supplement', catalogSlide: 34, isSeeded: true },
  { name: 'Myneph+', category: 'Capsules', composition: 'Methylcobalamin + Pregabalin 75mg', description: 'Neuropathic pain management', catalogSlide: 35, isSeeded: true },
  { name: 'Natahit', category: 'Eye Drops', composition: 'Natamycin 5%', description: 'Antifungal for fungal keratitis & blepharitis', catalogSlide: 36, isSeeded: true },
  { name: 'Nepadot', category: 'Eye Drops', composition: 'Nepafenac 0.1%', description: 'NSAID for post-cataract surgery pain & inflammation', catalogSlide: 37, isSeeded: true },
  { name: 'Nepadot-HS', category: 'Eye Drops', composition: 'Nepafenac 0.3%', description: 'High-strength NSAID for post-surgical inflammation', catalogSlide: 38, isSeeded: true },
  { name: 'Okafine Gel', category: 'Eye Gel', composition: 'Dexpanthenol 5%', description: 'Corneal repair and ocular surface healing gel', catalogSlide: 84, isSeeded: true },
  { name: 'Okamoist', category: 'Eye Drops', composition: 'Hydroxypropyl Methylcellulose 0.3%', description: 'Artificial tears for dry eye comfort', catalogSlide: 39, isSeeded: true },
  { name: 'Oxket', category: 'Eye Drops', composition: 'Ofloxacin 0.3%', description: 'Fluoroquinolone antibiotic for bacterial conjunctivitis', catalogSlide: 40, isSeeded: true },
  { name: 'Oxket-DX', category: 'Eye Drops', composition: 'Ofloxacin 0.3% + Dexamethasone 0.1%', description: 'Antibiotic-steroid combo for bacterial inflammation', catalogSlide: 41, isSeeded: true },
  { name: 'Oxket-MF', category: 'Eye Drops', composition: 'Ofloxacin 0.3% + Fluorometholone 0.1%', description: 'Antibiotic with mild steroid for ocular infections', catalogSlide: 42, isSeeded: true },
  { name: 'Oxket-OF', category: 'Eye Ointment', composition: 'Ofloxacin 0.3%', description: 'Antibiotic ointment for bacterial eye infections', catalogSlide: 43, isSeeded: true },
  { name: 'Oxket-Plus', category: 'Eye Drops', composition: 'Ofloxacin 0.3% + Prednisolone 1%', description: 'Antibiotic-steroid for steroid-responsive infections', catalogSlide: 44, isSeeded: true },
  { name: 'Oxkit', category: 'Eye Drops', composition: 'Ofloxacin 0.3% + Ketorolac 0.5%', description: 'Antibiotic + NSAID for infected inflamed eyes', catalogSlide: 45, isSeeded: true },
  { name: 'Polyworth', category: 'Eye Drops', composition: 'Polymyxin B + Chloramphenicol', description: 'Broad-spectrum antibiotic combination', catalogSlide: 47, isSeeded: true },
  { name: 'Polyworth-DX', category: 'Eye Drops', composition: 'Polymyxin B + Chloramphenicol + Dexamethasone', description: 'Antibiotic-steroid triple combo', catalogSlide: 48, isSeeded: true },
  { name: 'Predohit', category: 'Eye Drops', composition: 'Prednisolone Acetate 1%', description: 'Potent steroid for post-operative & inflammatory conditions', catalogSlide: 49, isSeeded: true },
  { name: 'Ralcafit', category: 'Capsules', composition: 'Calcium + Calcitriol + Zinc + Magnesium', description: 'Bone & mineral supplement', catalogSlide: 50, isSeeded: true },
  { name: 'Ratroday', category: 'Capsules', composition: 'Retinol + Lutein + Zeaxanthin + Vitamins + Minerals', description: 'Comprehensive eye nutrition supplement', catalogSlide: 51, isSeeded: true },
  { name: 'Realgano', category: 'Eye Drops', composition: 'Brimonidine 0.15%', description: 'Alpha-2 agonist for glaucoma & ocular hypertension', catalogSlide: 52, isSeeded: true },
  { name: 'Realhyper-5', category: 'Eye Drops', composition: 'Sodium Chloride 5%', description: 'Hypertonic saline for corneal edema', catalogSlide: 53, isSeeded: true },
  { name: 'Realhyper-6', category: 'Eye Ointment', composition: 'Sodium Chloride 6%', description: 'Hypertonic ointment for corneal edema', catalogSlide: 53, isSeeded: true },
  { name: 'Realmega Gold', category: 'Capsules', composition: 'Omega-3 + Lutein + Zeaxanthin + Astaxanthin + Multivitamins', description: 'Premium eye nutrition & retinal health support', catalogSlide: 54, isSeeded: true },
  { name: 'Realmega-I', category: 'Capsules', composition: 'Omega-3 Fatty Acids 1000mg', description: 'Essential fatty acids for dry eye & retinal health', catalogSlide: 55, isSeeded: true },
  { name: 'Realmega Plus', category: 'Capsules', composition: 'Omega-3 + Lutein + Zeaxanthin + Vitamins', description: 'Enhanced eye nutrition supplement', catalogSlide: 56, isSeeded: true },
  { name: 'Realtravo', category: 'Eye Drops', composition: 'Travoprost 0.004%', description: 'Prostaglandin analogue for glaucoma & IOP reduction', catalogSlide: 57, isSeeded: true },
  { name: 'Realtravo-TM', category: 'Eye Drops', composition: 'Travoprost 0.004% + Timolol 0.5%', description: 'Dual-action IOP reduction for glaucoma', catalogSlide: 89, isSeeded: true },
  { name: 'Realtob Eye Drops', category: 'Eye Drops', composition: 'Tobramycin 0.3%', description: 'Aminoglycoside antibiotic for bacterial conjunctivitis', catalogSlide: 58, isSeeded: true },
  { name: 'Realtob Ointment', category: 'Eye Ointment', composition: 'Tobramycin 0.3%', description: 'Antibiotic ointment for bacterial eye infections', catalogSlide: 59, isSeeded: true },
  { name: 'Realtob-DX', category: 'Eye Drops', composition: 'Tobramycin 0.3% + Dexamethasone 0.1%', description: 'Antibiotic-steroid for inflammatory infections', catalogSlide: 60, isSeeded: true },
  { name: 'Realtob-F', category: 'Eye Drops', composition: 'Tobramycin 0.3% + Fluorometholone 0.1%', description: 'Antibiotic with mild steroid', catalogSlide: 61, isSeeded: true },
  { name: 'Realtob-LP', category: 'Eye Drops', composition: 'Tobramycin 0.3% + Loteprednol 0.5%', description: 'Antibiotic + soft steroid combination', catalogSlide: 62, isSeeded: true },
  { name: 'Relzit Eye Drops', category: 'Eye Drops', composition: 'Azithromycin 1%', description: 'Macrolide antibiotic for bacterial conjunctivitis', catalogSlide: 63, isSeeded: true },
  { name: 'Relzit Ointment', category: 'Eye Ointment', composition: 'Azithromycin 1%', description: 'Antibiotic ointment for bacterial eye infections', catalogSlide: 64, isSeeded: true },
  { name: 'Self-Quin Eye Drops', category: 'Eye Drops', composition: 'Moxifloxacin 0.5%', description: 'Fourth-generation fluoroquinolone for bacterial infections', catalogSlide: 65, isSeeded: true },
  { name: 'Self-Quin Ointment', category: 'Eye Ointment', composition: 'Moxifloxacin 0.5%', description: 'Antibiotic ointment for bacterial conjunctivitis', catalogSlide: 66, isSeeded: true },
  { name: 'Self-Quin Gel', category: 'Eye Gel', composition: 'Moxifloxacin 0.5%', description: 'Antibiotic gel formulation', catalogSlide: 67, isSeeded: true },
  { name: 'Self-Quin D', category: 'Eye Drops', composition: 'Moxifloxacin 0.5% + Dexamethasone 0.1%', description: 'Antibiotic-steroid for steroid-responsive infections', catalogSlide: 68, isSeeded: true },
  { name: 'Self-Quin LP', category: 'Eye Drops', composition: 'Moxifloxacin 0.5% + Loteprednol 0.5%', description: 'Antibiotic + soft steroid combination', catalogSlide: 69, isSeeded: true },
  { name: 'Self-Quin KT', category: 'Eye Drops', composition: 'Moxifloxacin 0.5% + Ketorolac 0.5%', description: 'Antibiotic + NSAID for infected inflamed eyes', catalogSlide: 70, isSeeded: true },
  { name: 'Self-Quin P', category: 'Eye Drops', composition: 'Moxifloxacin 0.5% + Prednisolone 1%', description: 'Antibiotic-steroid for steroid-responsive inflammatory infections', catalogSlide: 71, isSeeded: true },
  { name: 'Self-Quin T', category: 'Eye Drops', composition: 'Moxifloxacin 0.5% + Tobramycin 0.3%', description: 'Dual antibiotic for superficial ocular infections', catalogSlide: 72, isSeeded: true },
  { name: 'Tacohit', category: 'Eye Ointment', composition: 'Tacrolimus 0.03%', description: 'Immunomodulator ointment for vernal keratoconjunctivitis', catalogSlide: 73, isSeeded: true },
  { name: 'Timoriz', category: 'Eye Drops', composition: 'Timolol Maleate 0.5%', description: 'Beta-blocker for open-angle glaucoma & IOP reduction', catalogSlide: 74, isSeeded: true },
  { name: 'Timoriz-BM', category: 'Eye Drops', composition: 'Timolol 0.5% + Brimonidine 0.2%', description: 'Dual-action IOP reduction for glaucoma', catalogSlide: 75, isSeeded: true },
  { name: 'Troriz-P', category: 'Eye Drops', composition: 'Tropicamide 0.8% + Phenylephrine 5%', description: 'Mydriatic for pupil dilation during diagnostics', catalogSlide: 76, isSeeded: true },
  { name: 'Vorisurge', category: 'Eye Drops', composition: 'Voriconazole 1%', description: 'Antifungal for fungal keratitis', catalogSlide: 77, isSeeded: true },
  { name: 'Yapat', category: 'Eye Drops', composition: 'Olopatadine 0.1%', description: 'Antihistamine for allergic conjunctivitis', catalogSlide: 80, isSeeded: true },
  { name: 'Yapat-KT', category: 'Eye Drops', composition: 'Olopatadine 0.1% + Ketorolac 0.4%', description: 'Anti-allergic + NSAID for allergic conjunctivitis', catalogSlide: 78, isSeeded: true },
  { name: 'Yapat-Max', category: 'Eye Drops', composition: 'Olopatadine HCl eq. to Olopatadine 0.7%', description: 'Maximum-strength once-daily anti-allergic', catalogSlide: 79, isSeeded: true },
  { name: 'Yapat-OD', category: 'Eye Drops', composition: 'Olopatadine HCl 0.2%', description: 'Once-daily anti-allergic for allergic conjunctivitis', catalogSlide: 80, isSeeded: true },
  { name: 'YesFlox Eye Drops', category: 'Eye Drops', composition: 'Gatifloxacin 0.3%', description: 'Fluoroquinolone antibiotic for bacterial conjunctivitis', catalogSlide: 82, isSeeded: true },
  { name: 'YesFlox Eye Ointment', category: 'Eye Ointment', composition: 'Gatifloxacin 0.3%', description: 'Antibiotic ointment for bacterial conjunctivitis', catalogSlide: 81, isSeeded: true },
  { name: 'YesFlox-HS', category: 'Eye Drops', composition: 'Gatifloxacin 0.5%', description: 'High-strength antibiotic for bacterial conjunctivitis', catalogSlide: 82, isSeeded: true },
  { name: 'YesFlox-KT', category: 'Eye Drops', composition: 'Gatifloxacin 0.3% + Ketorolac 0.4%', description: 'Antibiotic + NSAID for bacterial conjunctivitis with inflammation', catalogSlide: 83, isSeeded: true },
  { name: 'YesFlox-P', category: 'Eye Drops', composition: 'Gatifloxacin 0.3% + Prednisolone 1%', description: 'Antibiotic-steroid for steroid-responsive infections', catalogSlide: 85, isSeeded: true },
  { name: 'Yesflu-10', category: 'Tablets', composition: 'Flunarizine Dihydrochloride 10mg', description: 'Calcium channel blocker for glaucomatous optic neuropathy & migraine', catalogSlide: 86, isSeeded: true },
  { name: 'Yesflu-P', category: 'Tablets', composition: 'Flunarizine 10mg + Propranolol 40mg (SR)', description: 'Combination for migraine prophylaxis', catalogSlide: 87, isSeeded: true },
  { name: 'Yesflur', category: 'Eye Drops', composition: 'Flurbiprofen 0.03% + HPMC 0.025%', description: 'NSAID for inhibition of intraoperative miosis', catalogSlide: 88, isSeeded: true },
  { name: 'Yesflur-GT', category: 'Eye Drops', composition: 'Flurbiprofen 0.03% + Gatifloxacin 0.3%', description: 'NSAID + antibiotic for post-operative inflammation & infection', catalogSlide: 90, isSeeded: true },
  { name: 'Oxkit-D', category: 'Eye Drops', composition: 'Ofloxacin 0.3% + Dexamethasone 0.1% + Ketorolac 0.5%', description: 'Triple combo: antibiotic + steroid + NSAID', catalogSlide: 45, isSeeded: true },
];
